import { useState, useEffect, useCallback, useRef } from "react";

const SLIDES = [
  { id: "title", type: "title", emoji: "🍕", title: "Build a Chat Server\non a Raspberry Pi", subtitle: "A 90-minute journey from zero to running your own web server", footer: "Use ← → arrow keys or swipe to navigate" },
  { id: "what-we-build", type: "overview", emoji: "🗺️", title: "What We're Building Today", points: [{ icon: "🖥️", label: "A real web server", desc: "Running on your Raspberry Pi" }, { icon: "📱", label: "A chat app", desc: "You'll open it on your phone" }, { icon: "🌐", label: "A connected network", desc: "Everyone's servers talk to each other" }] },
  { id: "restaurant-1", type: "analogy", emoji: "🍽️", title: "The Internet is a Restaurant", text: "Every time you use the internet, you're a customer at a restaurant. Let's break it down.", visual: [{ role: "You (Phone/Laptop)", icon: "📱", label: "CLIENT", desc: "The customer who orders" }, { role: "WiFi / Internet", icon: "📡", label: "NETWORK", desc: "The waiter who carries orders" }, { role: "Raspberry Pi", icon: "🍳", label: "SERVER", desc: "The kitchen that makes food" }] },
  { id: "restaurant-2", type: "analogy-flow", emoji: "📨", title: "Request → Response", subtitle: "This is how EVERY website works. Every. Single. One.", steps: [{ icon: "📱", text: "You type a URL and hit Enter", label: "REQUEST", color: "#22d3ee" }, { icon: "📡", text: "Your request travels across the network", label: "NETWORK", color: "#a78bfa" }, { icon: "🍳", text: "The server receives it and does some work", label: "SERVER", color: "#fb923c" }, { icon: "📦", text: "The server sends back a response (a web page!)", label: "RESPONSE", color: "#4ade80" }, { icon: "📱", text: "Your browser renders it on screen", label: "RENDER", color: "#22d3ee" }] },
  { id: "what-is-server", type: "explainer", emoji: "🤔", title: "But What IS a Server?", blocks: [{ heading: "It's just a computer that listens", body: "A server is any computer running a program that waits for requests and sends back responses. That's it. Your Raspberry Pi is about to become one.", icon: "👂" }, { heading: "It has an address", body: "Just like a house has a street address, your Pi has an IP address (like 10.10.0.152). That's how other devices find it on the network.", icon: "🏠" }, { heading: "It has a port", body: "If the IP address is the building, the port is the apartment number. Our server runs on port 5000. One computer can run many servers on different ports.", icon: "🚪" }] },
  { id: "status-codes", type: "codes", emoji: "🔢", title: "HTTP Status Codes", subtitle: "When the server responds, it includes a number that says how things went.", codes: [{ code: "200", meaning: "OK", restaurant: "Here's your food! 🍔", color: "#4ade80" }, { code: "404", meaning: "Not Found", restaurant: "We don't serve that here 🤷", color: "#fb923c" }, { code: "500", meaning: "Server Error", restaurant: "The kitchen is on fire 🔥", color: "#f87171" }, { code: "403", meaning: "Forbidden", restaurant: "VIP area only 🚫", color: "#c084fc" }] },
  { id: "get-vs-post", type: "versus", emoji: "📬", title: "GET vs POST", subtitle: "HTTP has different 'verbs' for different actions — like different types of restaurant orders.", left: { method: "GET", color: "#22d3ee", tagline: "\"Give me something\"", examples: ["Loading a web page", "Checking for new messages", "Viewing a profile"], analogy: "Asking the waiter \"What's on the menu?\"" }, right: { method: "POST", color: "#fb923c", tagline: "\"Here, take this\"", examples: ["Sending a chat message", "Submitting a form", "Uploading a photo"], analogy: "Handing the waiter your order on a slip of paper" } },
  { id: "what-is-json", type: "json-explainer", emoji: "📦", title: "JSON: How Computers Talk", subtitle: "When your phone sends or receives data, it uses JSON — a simple format both humans and computers can read.", example: { user: "Alice", text: "Hello everyone!", server: "Pi-Alice", time: 1710432000 }, annotations: [{ key: "Curly braces { }", desc: "Wrap the whole thing — like an envelope" }, { key: "Keys (left side)", desc: "Labels — what kind of info this is" }, { key: "Values (right side)", desc: "The actual data" }, { key: "Quotes \" \"", desc: "Text goes in quotes, numbers don't" }] },
  { id: "architecture", type: "architecture", emoji: "🕸️", title: "Our Chat Network", description: "Star topology — every Pi talks through one central Hub" },
  { id: "step-wifi", type: "step", phase: "Phase 0", emoji: "📶", title: "Connect to WiFi", instructions: ["Connect your laptop to the workshop WiFi", "Check the whiteboard for the network name and password", "Make sure your phone is on the SAME WiFi too"], checkpoint: "Hold up your 🟢 green sticky when you're connected!" },
  { id: "step-ssh", type: "step", phase: "Phase 1", emoji: "🔑", title: "SSH Into Your Pi", instructions: ["Open a terminal on your laptop"], platforms: [{ os: "Windows", cmd: "Search 'PowerShell' in Start" }, { os: "Mac", cmd: "Cmd+Space → type 'Terminal'" }, { os: "Chromebook", cmd: "Open the Linux terminal" }], checkpoint: null },
  { id: "what-is-ssh", type: "explainer", emoji: "🔐", title: "What is SSH?", blocks: [{ heading: "A phone call to another computer", body: "SSH (Secure Shell) lets you type commands on your laptop that run on the Pi. It's like a remote control — but with text instead of buttons.", icon: "📞" }, { heading: "It's encrypted", body: "The \"Secure\" in SSH means everything you type is scrambled so nobody on the WiFi can snoop. That's why real engineers use it.", icon: "🔒" }, { heading: "It's how the real world works", body: "Almost every server on the internet — Instagram, Google, Netflix — is managed by engineers SSHing in. Exactly like you're about to do.", icon: "🌍" }] },
  { id: "step-ssh-2", type: "pi-table", phase: "Phase 1", emoji: "🔑", title: "Find Your Pi & SSH In", subtitle: "Find your assigned Pi below and type the SSH command in your terminal.", password: "HF", pis: [{ name: "hf-pi-1", cmd: "ssh hacker1@10.10.0.152" }, { name: "hf-pi-2", cmd: "ssh hacker2@10.10.7.248" }, { name: "hf-pi-3", cmd: "ssh hacker3@10.10.3.77" }, { name: "hf-pi-4", cmd: "ssh hacker4@10.10.2.157" }, { name: "hf-pi-5", cmd: "ssh hacker5@10.10.0.93" }, { name: "hf-pi-6", cmd: "ssh hacker6@10.10.4.250" }, { name: "hf-pi-7", cmd: "ssh hacker7@10.10.3.83" }, { name: "hf-pi-8", cmd: "ssh hacker8@10.10.4.241" }, { name: "hf-pi-9", cmd: "ssh hacker9@10.10.0.157" }], breakdown: [{ piece: "ssh", desc: "The program — \"I want a secure connection\"" }, { piece: "hacker1", desc: "Your username — like a login name" }, { piece: "@", desc: "The \"at\" symbol — separates user from address" }, { piece: "10.10.x.x", desc: "Your Pi's IP address on this network" }], warnings: [{ icon: "⚠️", title: "\"Are you sure?\" prompt", fix: "Type yes (the full word) and press Enter. This is normal!" }, { icon: "🔒", title: "Password is invisible", fix: "Nothing shows when you type — no dots, no stars. Type HF and press Enter." }], checkpoint: "When you see a $ prompt, hold up your 🟢 green sticky!" },
  { id: "step-ssh-3", type: "code-step", phase: "Phase 1", emoji: "👀", title: "Look Around Your Pi", code: "hostname\nhostname -I\nls", note: "Try each command one at a time. Hit Enter after each.", breakdown: [{ piece: "hostname", desc: "\"What's your name?\" — shows the Pi's name" }, { piece: "hostname -I", desc: "\"What's your address?\" — shows the Pi's IP" }, { piece: "ls", desc: "\"What files are here?\" — lists folder contents" }], warnings: [], checkpoint: null },
  { id: "what-is-terminal", type: "explainer", emoji: "⌨️", title: "The Terminal", blocks: [{ heading: "A text-only way to control a computer", body: "Before mice and icons existed, this was the ONLY way to use a computer. It's still the fastest and most powerful way — that's why developers love it.", icon: "🖥️" }, { heading: "You type a command, it does a thing", body: "Every command is a tiny program. ls lists files, cd changes folders, python3 runs Python code. Simple as that.", icon: "▶️" }, { heading: "Don't be afraid to mess up", body: "Type something wrong? You'll get an error message — not an explosion. Read the error, try again. That's what professional engineers do all day.", icon: "💪" }] },
  { id: "step-download", type: "code-step", phase: "Phase 1", emoji: "📥", title: "Download the Chat Server Code", code: "wget https://vision-hack-rpi-workshop-2026.vercel.app/chat-server.tar.gz\ntar xzf chat-server.tar.gz\nls chat-server", note: "Type the wget line carefully — or copy it from vision-hack-rpi-workshop-2026.vercel.app", breakdown: [{ piece: "wget", desc: "\"Web get\" — downloads a file from a URL, like clicking a download link" }, { piece: "https://...", desc: "The address of the file — hosted on our workshop website" }, { piece: "tar", desc: "A tool for packing/unpacking file archives (like .zip but for Linux)" }, { piece: "xzf", desc: "x = extract, z = decompress gzip, f = from this file" }, { piece: "chat-server.tar.gz", desc: "The compressed archive — contains all the server code" }, { piece: "ls chat-server", desc: "Peek inside — you should see app.py, start.sh, and templates/" }], warnings: [{ icon: "⚠️", title: "\"wget: command not found\"", fix: "Try instead: curl -O https://vision-hack-rpi-workshop-2026.vercel.app/chat-server.tar.gz" }, { icon: "⚠️", title: "Download fails or times out", fix: "Make sure your Pi is connected to the workshop WiFi. Ask an instructor for help." }], checkpoint: "Run ls chat-server — see app.py and templates/? 🟢 Green sticky!" },
  { id: "step-launch", type: "code-step", phase: "Phase 2", emoji: "🚀", title: "Launch Your Chat Server", code: "cd chat-server\nbash start.sh", note: "You should see: 🚀 CHANGE-ME's chat server starting!", breakdown: [{ piece: "cd chat-server", desc: "\"Change directory\" — walk into the chat-server folder" }, { piece: "bash", desc: "\"Run this shell script\" — bash is the program that reads the script" }, { piece: "start.sh", desc: "A short script that activates Python and runs your server" }], warnings: [{ icon: "🔧", title: "\"Address already in use\"", fix: "Type: sudo fuser -k 5000/tcp then bash start.sh again" }, { icon: "🔧", title: "\"No such file or directory\"", fix: "Make sure you ran cd chat-server first — you need to be inside the folder." }], checkpoint: "See 'Running on http://0.0.0.0:5000'? 🟢 Green sticky up!" },
  { id: "what-start-sh-does", type: "code-anatomy", emoji: "🔑", title: "What start.sh Does Behind the Scenes", subtitle: "start.sh is a shortcut. Here's what it runs for you — you could type these commands yourself.", codeLines: [{ code: "source venv/bin/activate", annotation: "Turn on the Python virtual environment (where Flask is installed)", color: "#a78bfa" }, { code: "", annotation: "", color: "transparent" }, { code: "python3 app.py", annotation: "Run your server! Python reads app.py and starts Flask on port 5000", color: "#4ade80" }], routes: [] },
  { id: "what-is-python", type: "explainer", emoji: "🐍", title: "Python & Virtual Environments", blocks: [{ heading: "python3 runs a Python program", body: "When you type python3 app.py, you're telling the Pi: \"Use Python to run the code in this file.\" app.py is your entire chat server — routes, messages, everything.", icon: "▶️" }, { heading: "A virtual environment (venv) keeps things tidy", body: "venv is a folder that holds Flask and other libraries just for this project. source venv/bin/activate tells the terminal: \"Use the Python and libraries in here.\" Without it, Python won't know what Flask is.", icon: "📦" }, { heading: "You can run it manually too", body: "Instead of bash start.sh, you could type: source venv/bin/activate then python3 app.py. Same result! The script just saves you typing.", icon: "⌨️" }] },
  { id: "what-just-happened", type: "explainer", emoji: "🧠", title: "What Just Happened?", blocks: [{ heading: "Your Pi is now listening on port 5000", body: "Flask (a Python library) started a web server. It's sitting there waiting: \"Is anyone going to send me a request?\" Like a kitchen with the lights on, ready for orders.", icon: "👂" }, { heading: "0.0.0.0 means \"accept from anyone\"", body: "That address means your Pi accepts connections from any device on the network — not just itself. That's what lets your phone connect.", icon: "🌐" }, { heading: "It registered with the Hub", body: "Your server automatically told the Hub: \"I exist! Here's my name and address.\" Now the Hub knows where to forward messages to you.", icon: "📡" }] },
  { id: "step-phone", type: "magic", phase: "Phase 2", emoji: "✨", title: "The Magic Moment", instruction: "On your phone, open a browser and go to:", url: "http://YOUR-PI-IP:5000", note: "Use your Pi's IP from the SSH slide (e.g. http://10.10.0.152:5000)", reveal: "That chat page is NOT on the internet. It's coming directly from that tiny Raspberry Pi in front of you, through the WiFi, to your phone. You are running a real web server right now." },
  { id: "what-happened-phone", type: "request-trace", emoji: "🔍", title: "What Just Happened on Your Phone?", subtitle: "When you typed that URL and hit Enter, here's exactly what happened:", steps: [{ actor: "📱 Your Phone", action: "Sent an HTTP GET request to your Pi on port 5000", path: "GET /" }, { actor: "📡 WiFi Router", action: "Carried that request to your Pi", path: "" }, { actor: "🍳 Flask on your Pi", action: "Received the request and matched it to the / route", path: "@app.route('/')" }, { actor: "🍳 The home() function", action: "Loaded the chat.html template file", path: "render_template('chat.html')" }, { actor: "📡 WiFi Router", action: "Sent the HTML back to your phone", path: "200 OK + HTML" }, { actor: "📱 Your Browser", action: "Rendered the HTML, CSS, and JavaScript as a chat page", path: "💬 Chat appears!" }] },
  { id: "anatomy-routes", type: "code-anatomy", emoji: "🗺️", title: "Routes: The Server's Menu", subtitle: "A route tells Flask: \"When someone asks for THIS address, run THIS function.\" Like a restaurant menu — each item has a name and a recipe.", codeLines: [{ code: "@app.route('/')", annotation: "The decorator — tells Flask which URL triggers this", color: "#a78bfa" }, { code: "def home():", annotation: "The function that runs when someone visits '/'", color: "#22d3ee" }, { code: "    return render_template('chat.html')", annotation: "The response — send back the chat page", color: "#4ade80" }], routes: [{ path: "/", method: "GET", does: "Shows the chat page", analogy: "\"The front door\"" }, { path: "/api/messages", method: "GET", does: "Returns messages as JSON", analogy: "\"Any new messages?\"" }, { path: "/api/send", method: "POST", does: "Accepts a new message", analogy: "\"Here's a new message\"" }, { path: "/incoming", method: "POST", does: "Receives from hub", analogy: "\"Mail from another server\"" }] },
  { id: "step-cross", type: "step", phase: "Phase 2", emoji: "💬", title: "Cross-Server Chat", instructions: ["Type your name in the name field", "Send a message from your phone", "Wait 2-3 seconds...", "Look — messages from OTHER servers appear!"], checkpoint: "Can you see messages from other servers? 🟢 Green sticky!", insight: "That 2-second delay? Your phone asks your Pi \"any new messages?\" every 2 seconds. That's called polling. Your email app does the same thing." },
  { id: "how-polling", type: "polling-demo", emoji: "🔄", title: "How Polling Works", description: "Your phone keeps asking the server: 'Anything new?' — over and over, every 2 seconds. Watch it in action." },
  { id: "polling-code", type: "code-anatomy", emoji: "⏱️", title: "The Polling Code", subtitle: "This JavaScript runs in your phone's browser (chat.html). It's the CLIENT code that talks to your server.", codeLines: [{ code: "setInterval(fetchMessages, 2000);", annotation: "\"Run fetchMessages every 2000 ms (2 seconds)\"", color: "#fbbf24" }, { code: "", annotation: "", color: "transparent" }, { code: "function fetchMessages() {", annotation: "This function runs automatically, again and again:", color: "#22d3ee" }, { code: "  fetch('/api/messages?after=' + seen)", annotation: "GET request: \"give me messages after what I've seen\"", color: "#4ade80" }, { code: "    .then(r => r.json())", annotation: "Parse the response as JSON data", color: "#a78bfa" }, { code: "    .then(msgs => { /* show them */ })", annotation: "Loop through new messages, add them to the page", color: "#fb923c" }, { code: "}", annotation: "", color: "transparent" }], routes: [] },
  { id: "how-send-works", type: "code-anatomy", emoji: "📤", title: "What Happens When You Hit Send", subtitle: "When you tap Send, the JavaScript in chat.html runs this code on your phone:", codeLines: [{ code: "fetch('/api/send', {", annotation: "Talk to YOUR Pi's /api/send route", color: "#22d3ee" }, { code: "  method: 'POST',", annotation: "POST because we're SENDING data, not asking", color: "#fb923c" }, { code: "  headers: {", annotation: "Tell the server the format:", color: "#a78bfa" }, { code: "    'Content-Type': 'application/json'", annotation: "\"I'm sending you JSON\"", color: "#a78bfa" }, { code: "  },", annotation: "", color: "transparent" }, { code: "  body: JSON.stringify({", annotation: "Package up the data:", color: "#fbbf24" }, { code: "    user: 'Alice', text: 'Hello!'", annotation: "Your name and your message", color: "#4ade80" }, { code: "  })", annotation: "", color: "transparent" }, { code: "})", annotation: "One request — and your message is sent!", color: "rgba(255,255,255,0.3)" }], routes: [] },
  { id: "server-receives", type: "code-anatomy", emoji: "📥", title: "The Server Receives Your Message", subtitle: "Back on the Pi, Flask catches that POST and runs this Python code in app.py:", codeLines: [{ code: "@app.route('/api/send', methods=['POST'])", annotation: "Only respond to POST requests at this address", color: "#a78bfa" }, { code: "def send_message():", annotation: "This function runs when someone POSTs here", color: "#22d3ee" }, { code: "    data = request.json", annotation: "Extract the JSON the phone sent", color: "#fbbf24" }, { code: "    msg = {'user': ..., 'text': ...}", annotation: "Build a message with user, text, server name, time", color: "#fb923c" }, { code: "    messages.append(msg)", annotation: "Add it to our Python list (our \"database\")", color: "#4ade80" }, { code: "    http_client.post(HUB+'/relay', json=msg)", annotation: "Forward to the Hub so others get it too", color: "#a78bfa" }, { code: "    return jsonify({'status': 'ok'})", annotation: "Tell the phone: \"Got it!\" (200 OK)", color: "#4ade80" }], routes: [] },
  { id: "how-hub-works", type: "hub-explainer", emoji: "🌐", title: "How the Hub Connects Everyone", subtitle: "Without the Hub, each Pi is an island. The Hub is the post office — it delivers mail between all servers.", steps: [{ num: "1", text: "Your Pi receives a message from your phone", icon: "📱→🍳" }, { num: "2", text: "Your Pi saves it AND sends a copy to the Hub", icon: "🍳→🌐" }, { num: "3", text: "The Hub loops through ALL registered servers", icon: "🌐🔄" }, { num: "4", text: "For each OTHER server, Hub sends POST /incoming", icon: "🌐→🍳" }, { num: "5", text: "Each Pi saves it. Phones pick it up on next poll.", icon: "🍳→📱" }], key_insight: "If the Hub goes down, local chat still works — you just can't see other servers' messages. The code handles this with try/except (tries the Hub, but keeps going if it fails)." },
  { id: "anatomy-full", type: "file-map", emoji: "📁", title: "Every File and What It Does", subtitle: "Your entire chat server is only 3 files. Here's what each one does — and where the code runs.", files: [{ name: "app.py", role: "The brain", icon: "🧠", color: "#22d3ee", desc: "Python code that runs ON THE PI. Defines routes, stores messages in a list, and talks to the Hub. This is the SERVER — the kitchen." }, { name: "templates/chat.html", role: "The face", icon: "🎨", color: "#fb923c", desc: "HTML + CSS + JavaScript that runs ON YOUR PHONE in the browser. Draws the UI, sends messages with fetch(), polls every 2 seconds. This is the CLIENT." }, { name: "start.sh", role: "The ignition key", icon: "🔑", color: "#4ade80", desc: "A tiny bash script that activates the Python environment and runs app.py. Just a convenience — you could type the commands yourself." }] },
  { id: "client-vs-server-code", type: "versus", emoji: "⚡", title: "Client Code vs Server Code", subtitle: "One of the most important ideas in web development: the same app has code running in TWO different places.", left: { method: "SERVER", color: "#22d3ee", tagline: "Runs on the Pi (app.py — Python)", examples: ["Has access to ALL messages", "Talks to the Hub and other servers", "Runs 24/7 until you Ctrl+C", "One copy serves many clients"], analogy: "The kitchen — processes orders, manages inventory, coordinates with other kitchens" }, right: { method: "CLIENT", color: "#fb923c", tagline: "Runs in the browser (chat.html — JS)", examples: ["Only knows what the server tells it", "Sends GET and POST requests", "Runs only while the tab is open", "Each phone runs its own copy"], analogy: "The customer — reads the menu, places orders, sees only what's brought to the table" } },
  { id: "customize-intro", type: "step", phase: "Phase 3", emoji: "🎨", title: "Make It Yours", instructions: ["Open a NEW terminal window (keep the server running!)", "SSH in again with the same command as before", "You now have two terminals: one running the server, one for editing"], checkpoint: null, insight: "After editing a file, stop the server with Ctrl+C then restart with bash start.sh for changes to take effect." },
  { id: "nano-intro", type: "explainer", emoji: "📝", title: "Using nano (Text Editor)", blocks: [{ heading: "Open a file", body: "Type nano app.py to open it. The file fills your terminal. Arrow keys to move around.", icon: "📂" }, { heading: "Edit like normal", body: "Just type! There's no special mode. Type, backspace, arrow keys — it all works as expected.", icon: "✏️" }, { heading: "Save: Ctrl+O → Enter", body: "Press Ctrl and O together (O for Output). It asks for a filename — just hit Enter to keep the same name.", icon: "💾" }, { heading: "Exit: Ctrl+X", body: "Press Ctrl and X together (X for eXit). If you forgot to save, it'll ask — press Y then Enter.", icon: "🚪" }] },
  { id: "customize-l1", type: "challenge", phase: "Phase 3", emoji: "⭐", level: 1, title: "Level 1: Personalize", tasks: [{ label: "Change your server name", file: "app.py", find: 'MY_NAME = "CHANGE-ME"', replace: 'MY_NAME = "YOUR-NAME"' }, { label: "Change your chat color", file: "templates/chat.html", find: "color: #1565c0", replace: "color: #e91e63" }], colors: [{ name: "Pink", hex: "#e91e63" }, { name: "Green", hex: "#4caf50" }, { name: "Orange", hex: "#ff9800" }, { name: "Purple", hex: "#9c27b0" }, { name: "Teal", hex: "#009688" }], editorSteps: ["nano app.py", "Find and change MY_NAME", "Ctrl+O → Enter → Ctrl+X", "Stop server: Ctrl+C", "Restart: bash start.sh", "Refresh your phone!"] },
  { id: "why-restart", type: "explainer", emoji: "🔁", title: "Why Do We Restart?", blocks: [{ heading: "The server loaded your code at startup", body: "Flask read app.py into memory when it started. Changing the file on disk doesn't change memory — like editing a recipe book doesn't change a meal already cooked.", icon: "📖" }, { heading: "Ctrl+C kills the running server", body: "Stops the Python process. Port 5000 is free. All messages vanish (they were just a Python list, not saved to disk).", icon: "🛑" }, { heading: "bash start.sh reads the NEW code", body: "Flask re-reads your files fresh. Changes are live! In pro setups, \"hot reload\" does this automatically.", icon: "🚀" }] },
  { id: "customize-l2", type: "challenge", phase: "Phase 3", emoji: "⭐⭐", level: 2, title: "Level 2: Modify Behavior", tasks: [{ label: "Speed up polling (faster messages!)", file: "templates/chat.html", find: "setInterval(fetchMessages, 2000)", replace: "setInterval(fetchMessages, 500)" }, { label: "Add emoji to every message", file: "app.py", find: "messages.append(msg)", replace: "msg['text'] = '🔥 ' + msg['text']\n    messages.append(msg)" }], colors: [], editorSteps: [], followUp: "When you changed 2000→500, your phone now polls 4x faster. Tradeoff: faster updates but more server load. With 10 users at 500ms = 20 req/sec instead of 5. Real engineering!" },
  { id: "customize-l3", type: "challenge", phase: "Phase 3", emoji: "⭐⭐⭐", level: 3, title: "Level 3: Build a Feature", tasks: [{ label: "Add a /api/status endpoint", file: "app.py", find: "(add after the last @app.route block)", replace: "@app.route('/api/status')\ndef status():\n    return jsonify({\n        'server': MY_NAME,\n        'messages': len(messages),\n        'uptime': 'running!'\n    })" }], colors: [], editorSteps: ["Visit http://your-ip:5000/api/status", "You'll see raw JSON — this is what APIs look like!", "Every app (Instagram, Spotify) has APIs just like this"] },
  { id: "message-journey", type: "journey", emoji: "🗺️", title: "The Full Journey of a Message", description: "Let's trace exactly what happens from typing 'hello' to everyone seeing it." },
  { id: "real-world", type: "realworld", emoji: "🌍", title: "You Just Built the Internet", comparisons: [{ you: "Flask on a Pi", real: "Millions of servers", label: "Server" }, { you: "Python list", real: "Databases (PostgreSQL)", label: "Storage" }, { you: "/api/messages", real: "REST & GraphQL APIs", label: "API" }, { you: "fetch() polling", real: "WebSockets, SSE", label: "Real-time" }, { you: "Hub relay", real: "Message queues (Kafka)", label: "Network" }, { you: "1 user per Pi", real: "Millions concurrent", label: "Scale" }], punchline: "The gap between what you built and what runs Instagram is scale, not concept." },
  { id: "what-you-did", type: "wrapup", emoji: "🏆", title: "What You Actually Did Today", achievements: [{ icon: "🔑", text: "SSHed into a remote Linux server" }, { icon: "🖥️", text: "Ran a real web server handling HTTP requests" }, { icon: "🐍", text: "Read and modified production Python code" }, { icon: "📱", text: "Connected a client (phone) to a server (Pi) you built" }, { icon: "🔧", text: "Debugged a distributed, multi-server system" }, { icon: "🌐", text: "Built a networked app with real client-server architecture" }], closing: "A Raspberry Pi costs ~$35. Python and Flask are free. Everything you need to keep learning is free online. Keep building. 🚀" },
];

// ============ COMPONENTS ============

function ProgressBar({ current, total }) {
  return <div style={{ position: "fixed", top: 0, left: 0, right: 0, height: 3, zIndex: 100, background: "rgba(255,255,255,0.06)" }}>
    <div style={{ height: "100%", width: `${((current + 1) / total) * 100}%`, background: "linear-gradient(90deg, #22d3ee, #a78bfa)", transition: "width 0.4s cubic-bezier(0.4,0,0.2,1)", borderRadius: "0 2px 2px 0" }} />
  </div>;
}

function SlideNav({ current, total, onPrev, onNext }) {
  const btnBase = { pointerEvents: "auto", border: "1px solid rgba(255,255,255,0.15)", padding: "8px 18px", borderRadius: 8, fontSize: 14, fontFamily: "var(--mono)", transition: "all 0.2s" };
  return <div style={{ position: "fixed", bottom: 0, left: 0, right: 0, display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 24px", background: "linear-gradient(transparent, rgba(10,10,20,0.95))", zIndex: 90, pointerEvents: "none" }}>
    <button onClick={onPrev} disabled={current === 0} style={{ ...btnBase, background: "none", color: current === 0 ? "rgba(255,255,255,0.2)" : "rgba(255,255,255,0.7)", cursor: current === 0 ? "default" : "pointer" }}>← Prev</button>
    <span style={{ color: "rgba(255,255,255,0.4)", fontSize: 13, fontFamily: "var(--mono)", pointerEvents: "auto" }}>{current + 1} / {total}</span>
    <button onClick={onNext} disabled={current === total - 1} style={{ ...btnBase, background: current === total - 1 ? "none" : "linear-gradient(135deg, #22d3ee, #a78bfa)", border: current === total - 1 ? btnBase.border : "none", color: current === total - 1 ? "rgba(255,255,255,0.2)" : "#fff", cursor: current === total - 1 ? "default" : "pointer", fontWeight: 600 }}>Next →</button>
  </div>;
}

const PhaseBadge = ({ phase }) => phase ? <span style={{ display: "inline-block", background: "rgba(167,139,250,0.15)", border: "1px solid rgba(167,139,250,0.3)", color: "#c4b5fd", fontSize: 12, fontWeight: 700, padding: "3px 10px", borderRadius: 20, fontFamily: "var(--mono)", letterSpacing: 1, textTransform: "uppercase", marginBottom: 10 }}>{phase}</span> : null;
const CheckpointBox = ({ text }) => text ? <div style={{ background: "rgba(74,222,128,0.08)", border: "1px solid rgba(74,222,128,0.25)", borderRadius: 10, padding: "14px 18px", marginTop: 18, display: "flex", gap: 12 }}><span style={{ fontSize: 20 }}>✅</span><span style={{ color: "#86efac", fontSize: 15, lineHeight: 1.5, fontWeight: 500 }}>{text}</span></div> : null;
const InsightBox = ({ text }) => text ? <div style={{ background: "rgba(251,191,36,0.06)", border: "1px solid rgba(251,191,36,0.2)", borderRadius: 10, padding: "14px 18px", marginTop: 14, display: "flex", gap: 12 }}><span style={{ fontSize: 18 }}>💡</span><span style={{ color: "#fde68a", fontSize: 14, lineHeight: 1.5 }}>{text}</span></div> : null;
const Heading = ({ emoji, title, subtitle }) => <><h2 style={{ fontSize: 28, fontWeight: 800, color: "#fff", marginBottom: subtitle ? 6 : 20, fontFamily: "var(--mono)" }}><span style={{ marginRight: 10 }}>{emoji}</span>{title}</h2>{subtitle && <p style={{ color: "rgba(255,255,255,0.45)", fontSize: 14, marginBottom: 24, lineHeight: 1.5 }}>{subtitle}</p>}</>;
const Wrap = ({ children }) => <div style={{ padding: "60px 24px", maxWidth: 680, margin: "0 auto" }}>{children}</div>;

// ============ SLIDE TYPES ============

const TitleSlide = ({ slide: s }) => <div style={{ display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", minHeight: "85vh", textAlign: "center", padding: "0 20px" }}>
  <div style={{ fontSize: 72, marginBottom: 20 }}>{s.emoji}</div>
  <h1 style={{ fontSize: "clamp(32px, 6vw, 56px)", fontWeight: 800, lineHeight: 1.1, fontFamily: "var(--mono)", background: "linear-gradient(135deg, #22d3ee 0%, #a78bfa 50%, #fb923c 100%)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", whiteSpace: "pre-line", marginBottom: 20 }}>{s.title}</h1>
  <p style={{ color: "rgba(255,255,255,0.5)", fontSize: 18, maxWidth: 480, lineHeight: 1.5 }}>{s.subtitle}</p>
  <p style={{ color: "rgba(255,255,255,0.25)", fontSize: 13, marginTop: 40, fontFamily: "var(--mono)" }}>{s.footer}</p>
</div>;

const OverviewSlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} /><div style={{ display: "flex", flexDirection: "column", gap: 16 }}>{s.points.map((p, i) => <div key={i} style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 14, padding: "20px 24px", display: "flex", alignItems: "center", gap: 18 }}><span style={{ fontSize: 36 }}>{p.icon}</span><div><div style={{ color: "#fff", fontSize: 18, fontWeight: 700 }}>{p.label}</div><div style={{ color: "rgba(255,255,255,0.5)", fontSize: 14, marginTop: 2 }}>{p.desc}</div></div></div>)}</div></Wrap>;

const AnalogySlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.text} /><div style={{ display: "flex", flexDirection: "column", gap: 14 }}>{s.visual.map((v, i) => <div key={i} style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 14, padding: "20px 24px", display: "flex", alignItems: "center", gap: 18 }}><span style={{ fontSize: 40 }}>{v.icon}</span><div style={{ flex: 1 }}><div style={{ color: "#fff", fontSize: 16, fontWeight: 700 }}>{v.role}</div><div style={{ color: "rgba(255,255,255,0.45)", fontSize: 13, marginTop: 2 }}>{v.desc}</div></div><span style={{ fontFamily: "var(--mono)", fontSize: 11, background: "rgba(34,211,238,0.1)", color: "#22d3ee", padding: "4px 10px", borderRadius: 6, fontWeight: 700 }}>{v.label}</span></div>)}</div></Wrap>;

const AnalogyFlowSlide = ({ slide: s }) => <Wrap>{<Heading emoji={s.emoji} title={s.title} subtitle={s.subtitle} />}{s.steps.map((st, i) => <div key={i} style={{ display: "flex", gap: 18 }}><div style={{ display: "flex", flexDirection: "column", alignItems: "center", width: 40 }}><div style={{ width: 40, height: 40, borderRadius: "50%", background: `${st.color}15`, border: `1px solid ${st.color}40`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, flexShrink: 0 }}>{st.icon}</div>{i < s.steps.length - 1 && <div style={{ width: 2, flex: 1, minHeight: 24, background: `${st.color}25` }} />}</div><div style={{ paddingBottom: 20, flex: 1 }}><span style={{ fontFamily: "var(--mono)", fontSize: 10, fontWeight: 700, color: st.color, letterSpacing: 1.5, textTransform: "uppercase" }}>{st.label}</span><div style={{ color: "#fff", fontSize: 16, marginTop: 4, lineHeight: 1.4 }}>{st.text}</div></div></div>)}</Wrap>;

const ExplainerSlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} /><div style={{ display: "flex", flexDirection: "column", gap: 14 }}>{s.blocks.map((b, i) => <div key={i} style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 14, padding: "18px 20px" }}><div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}><span style={{ fontSize: 22 }}>{b.icon}</span><span style={{ color: "#fff", fontSize: 16, fontWeight: 700 }}>{b.heading}</span></div><p style={{ color: "rgba(255,255,255,0.55)", fontSize: 14, lineHeight: 1.6, marginLeft: 32 }}>{b.body}</p></div>)}</div></Wrap>;

const CodesSlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.subtitle} /><div style={{ display: "flex", flexDirection: "column", gap: 12 }}>{s.codes.map((c, i) => <div key={i} style={{ display: "flex", alignItems: "center", gap: 16, background: "rgba(255,255,255,0.03)", borderRadius: 12, padding: "14px 18px", borderLeft: `3px solid ${c.color}` }}><span style={{ fontFamily: "var(--mono)", fontSize: 28, fontWeight: 800, color: c.color, width: 60, flexShrink: 0 }}>{c.code}</span><div style={{ flex: 1 }}><div style={{ color: "rgba(255,255,255,0.4)", fontSize: 12, fontFamily: "var(--mono)" }}>{c.meaning}</div><div style={{ color: "#fff", fontSize: 16, marginTop: 2 }}>{c.restaurant}</div></div></div>)}</div></Wrap>;

const VersusSlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.subtitle} /><div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>{[s.left, s.right].map((side, i) => <div key={i} style={{ flex: "1 1 280px", background: `${side.color}08`, border: `1px solid ${side.color}25`, borderRadius: 14, padding: "18px 20px" }}><div style={{ fontFamily: "var(--mono)", fontSize: 22, fontWeight: 800, color: side.color, marginBottom: 4 }}>{side.method}</div><div style={{ color: "rgba(255,255,255,0.5)", fontSize: 13, marginBottom: 14, fontStyle: "italic" }}>{side.tagline}</div>{side.examples.map((ex, j) => <div key={j} style={{ color: "rgba(255,255,255,0.65)", fontSize: 13, padding: "4px 0", display: "flex", gap: 8 }}><span style={{ color: side.color }}>•</span>{ex}</div>)}<div style={{ marginTop: 14, background: "rgba(0,0,0,0.2)", borderRadius: 8, padding: "10px 12px", fontSize: 12, color: "rgba(255,255,255,0.4)", lineHeight: 1.4, fontStyle: "italic" }}>{side.analogy}</div></div>)}</div></Wrap>;

const JsonExplainerSlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.subtitle} /><pre style={{ background: "rgba(0,0,0,0.5)", border: "1px solid rgba(34,211,238,0.2)", borderRadius: 10, padding: "18px 22px", fontFamily: "var(--mono)", fontSize: 15, lineHeight: 1.7, color: "#22d3ee", overflowX: "auto", marginBottom: 20 }}>{JSON.stringify(s.example, null, 2)}</pre><div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{s.annotations.map((a, i) => <div key={i} style={{ display: "flex", gap: 12, alignItems: "baseline" }}><code style={{ fontFamily: "var(--mono)", fontSize: 12, color: "#a78bfa", flexShrink: 0, minWidth: 140 }}>{a.key}</code><span style={{ color: "rgba(255,255,255,0.5)", fontSize: 13 }}>{a.desc}</span></div>)}</div></Wrap>;

const ArchitectureSlide = ({ slide: s }) => { const nodes = [{ id: "hub", x: 50, y: 42, label: "HUB", emoji: "🌐", color: "#a78bfa" }, { id: "a", x: 18, y: 15, label: "Pi-Alice", emoji: "🍳", color: "#22d3ee" }, { id: "b", x: 82, y: 15, label: "Pi-Bob", emoji: "🍳", color: "#22d3ee" }, { id: "c", x: 14, y: 70, label: "Pi-Charlie", emoji: "🍳", color: "#22d3ee" }, { id: "d", x: 86, y: 70, label: "Pi-Dana", emoji: "🍳", color: "#22d3ee" }]; return <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.description} /><div style={{ position: "relative", width: "100%", paddingBottom: "65%", background: "rgba(0,0,0,0.3)", borderRadius: 16, border: "1px solid rgba(255,255,255,0.06)" }}><svg viewBox="0 0 100 65" style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }}>{nodes.filter(n => n.id !== "hub").map(n => <line key={n.id} x1={50} y1={42} x2={n.x} y2={n.y} stroke="rgba(167,139,250,0.25)" strokeWidth="0.4" strokeDasharray="1.5 1" />)}</svg>{nodes.map(n => <div key={n.id} style={{ position: "absolute", left: `${n.x}%`, top: `${n.y}%`, transform: "translate(-50%,-50%)", textAlign: "center" }}><div style={{ width: n.id === "hub" ? 52 : 40, height: n.id === "hub" ? 52 : 40, borderRadius: "50%", background: `${n.color}15`, border: `1.5px solid ${n.color}40`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: n.id === "hub" ? 24 : 18, margin: "0 auto" }}>{n.emoji}</div><div style={{ fontFamily: "var(--mono)", fontSize: 8, color: n.color, marginTop: 3, fontWeight: 700, whiteSpace: "nowrap" }}>{n.label}</div></div>)}{[{ x: 4, y: 3 }, { x: 96, y: 3 }, { x: 0, y: 82 }, { x: 100, y: 82 }].map((p, i) => <div key={i} style={{ position: "absolute", left: `${p.x}%`, top: `${p.y}%`, transform: "translate(-50%,-50%)", fontSize: 14, opacity: 0.5 }}>📱</div>)}</div><div style={{ display: "flex", justifyContent: "center", gap: 24, marginTop: 16, flexWrap: "wrap" }}>{["📱 Client", "🍳 Server (Pi)", "🌐 Hub"].map((t, i) => <span key={i} style={{ fontSize: 12, color: "rgba(255,255,255,0.35)" }}>{t}</span>)}</div></Wrap>; };

const StepSlide = ({ slide: s }) => <Wrap><PhaseBadge phase={s.phase} /><Heading emoji={s.emoji} title={s.title} /><div style={{ display: "flex", flexDirection: "column", gap: 10 }}>{s.instructions.map((inst, i) => <div key={i} style={{ display: "flex", gap: 14, alignItems: "flex-start", background: "rgba(255,255,255,0.03)", borderRadius: 10, padding: "14px 16px" }}><span style={{ fontFamily: "var(--mono)", fontSize: 14, fontWeight: 800, color: "#22d3ee", width: 24, flexShrink: 0, textAlign: "center" }}>{i + 1}</span><span style={{ color: "#fff", fontSize: 15, lineHeight: 1.5 }}>{inst}</span></div>)}</div>{s.platforms && <div style={{ display: "flex", gap: 8, marginTop: 16, flexWrap: "wrap" }}>{s.platforms.map((p, i) => <div key={i} style={{ background: "rgba(0,0,0,0.4)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 10, padding: "10px 14px", flex: "1 1 140px" }}><div style={{ fontFamily: "var(--mono)", fontSize: 12, fontWeight: 700, color: "#a78bfa", marginBottom: 4 }}>{p.os}</div><div style={{ color: "rgba(255,255,255,0.6)", fontSize: 13 }}>{p.cmd}</div></div>)}</div>}<InsightBox text={s.insight} /><CheckpointBox text={s.checkpoint} /></Wrap>;

const CodeStepSlide = ({ slide: s }) => <Wrap><PhaseBadge phase={s.phase} /><Heading emoji={s.emoji} title={s.title} subtitle={s.note} /><pre style={{ background: "rgba(0,0,0,0.5)", border: "1px solid rgba(34,211,238,0.2)", borderRadius: 10, padding: "18px 22px", fontFamily: "var(--mono)", fontSize: 17, lineHeight: 1.6, color: "#22d3ee", overflowX: "auto", margin: "12px 0" }}>{s.code.split("\n").map((l, i) => <div key={i}><span style={{ color: "rgba(255,255,255,0.2)", marginRight: 16, userSelect: "none", fontSize: 13 }}>{i + 1}</span>{l}</div>)}</pre>{s.breakdown && s.breakdown.length > 0 && <div style={{ marginTop: 16, display: "flex", flexDirection: "column", gap: 6 }}>{s.breakdown.map((b, i) => <div key={i} style={{ display: "flex", gap: 12, alignItems: "baseline" }}><code style={{ fontFamily: "var(--mono)", fontSize: 13, color: "#22d3ee", flexShrink: 0, background: "rgba(0,0,0,0.3)", padding: "2px 8px", borderRadius: 4 }}>{b.piece}</code><span style={{ color: "rgba(255,255,255,0.5)", fontSize: 13 }}>{b.desc}</span></div>)}</div>}{s.warnings.map((w, i) => <div key={i} style={{ background: "rgba(251,191,36,0.06)", border: "1px solid rgba(251,191,36,0.2)", borderRadius: 10, padding: "14px 16px", marginTop: 12, display: "flex", gap: 12 }}><span style={{ fontSize: 18 }}>{w.icon}</span><div><div style={{ color: "#fbbf24", fontSize: 14, fontWeight: 700 }}>{w.title}</div><div style={{ color: "rgba(255,255,255,0.55)", fontSize: 13, marginTop: 3, lineHeight: 1.4 }}>{w.fix}</div></div></div>)}<CheckpointBox text={s.checkpoint} /></Wrap>;

const MagicSlide = ({ slide: s }) => <div style={{ padding: "60px 24px", maxWidth: 600, margin: "0 auto", textAlign: "center" }}><PhaseBadge phase={s.phase} /><div style={{ fontSize: 64, marginBottom: 16 }}>{s.emoji}</div><h2 style={{ fontSize: 32, fontWeight: 800, color: "#fff", marginBottom: 16, fontFamily: "var(--mono)" }}>{s.title}</h2><p style={{ color: "rgba(255,255,255,0.6)", fontSize: 16, marginBottom: 24 }}>{s.instruction}</p><div style={{ background: "rgba(0,0,0,0.5)", border: "2px solid rgba(34,211,238,0.4)", borderRadius: 14, padding: "20px 24px", fontFamily: "var(--mono)", fontSize: "clamp(16px, 4vw, 24px)", color: "#22d3ee", fontWeight: 700, boxShadow: "0 0 40px rgba(34,211,238,0.1)" }}>{s.url}</div><p style={{ color: "rgba(255,255,255,0.4)", fontSize: 13, marginTop: 8, fontStyle: "italic" }}>{s.note}</p><div style={{ marginTop: 32, background: "rgba(74,222,128,0.06)", border: "1px solid rgba(74,222,128,0.2)", borderRadius: 14, padding: "20px 24px", textAlign: "left" }}><p style={{ color: "#86efac", fontSize: 16, lineHeight: 1.6, fontWeight: 500 }}>{s.reveal}</p></div></div>;

const RequestTraceSlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.subtitle} />{s.steps.map((st, i) => <div key={i} style={{ display: "flex", gap: 14, marginBottom: 2 }}><div style={{ display: "flex", flexDirection: "column", alignItems: "center", width: 36 }}><div style={{ width: 28, height: 28, borderRadius: "50%", background: "rgba(34,211,238,0.12)", border: "1px solid rgba(34,211,238,0.3)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontFamily: "var(--mono)", fontWeight: 800, color: "#22d3ee", flexShrink: 0 }}>{i + 1}</div>{i < s.steps.length - 1 && <div style={{ width: 1.5, flex: 1, minHeight: 8, background: "rgba(34,211,238,0.15)" }} />}</div><div style={{ paddingBottom: 12, flex: 1 }}><div style={{ fontFamily: "var(--mono)", fontSize: 11, fontWeight: 700, color: "#a78bfa", marginBottom: 2 }}>{st.actor}</div><div style={{ color: "rgba(255,255,255,0.7)", fontSize: 13, lineHeight: 1.4 }}>{st.action}</div>{st.path && <code style={{ fontFamily: "var(--mono)", fontSize: 11, color: "#4ade80", marginTop: 3, display: "inline-block" }}>{st.path}</code>}</div></div>)}</Wrap>;

const CodeAnatomySlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.subtitle} /><div style={{ display: "flex", flexDirection: "column", gap: 4, marginBottom: 24 }}>{s.codeLines.map((cl, i) => cl.code ? <div key={i} style={{ display: "flex", gap: 12, alignItems: "flex-start", flexWrap: "wrap" }}><code style={{ fontFamily: "var(--mono)", fontSize: 12, color: cl.color, background: "rgba(0,0,0,0.4)", padding: "4px 10px", borderRadius: 6, whiteSpace: "pre", borderLeft: `2px solid ${cl.color}`, flexShrink: 0 }}>{cl.code}</code>{cl.annotation && <span style={{ color: "rgba(255,255,255,0.45)", fontSize: 12, lineHeight: 1.4, paddingTop: 4 }}>{cl.annotation}</span>}</div> : <div key={i} style={{ height: 6 }} />)}</div>{s.routes && s.routes.length > 0 && <><div style={{ fontFamily: "var(--mono)", fontSize: 11, fontWeight: 700, color: "rgba(255,255,255,0.3)", marginBottom: 10, letterSpacing: 1.5, textTransform: "uppercase" }}>All Routes</div><div style={{ display: "flex", flexDirection: "column", gap: 6 }}>{s.routes.map((r, i) => <div key={i} style={{ display: "flex", alignItems: "center", gap: 10, background: "rgba(255,255,255,0.03)", borderRadius: 8, padding: "10px 14px", flexWrap: "wrap" }}><span style={{ fontFamily: "var(--mono)", fontSize: 10, fontWeight: 700, color: r.method === "GET" ? "#22d3ee" : "#fb923c", background: r.method === "GET" ? "rgba(34,211,238,0.12)" : "rgba(251,146,60,0.12)", padding: "2px 8px", borderRadius: 4 }}>{r.method}</span><code style={{ fontFamily: "var(--mono)", fontSize: 13, color: "#fff" }}>{r.path}</code><span style={{ color: "rgba(255,255,255,0.4)", fontSize: 12, flex: 1 }}>{r.does}</span><span style={{ color: "rgba(255,255,255,0.25)", fontSize: 11, fontStyle: "italic" }}>{r.analogy}</span></div>)}</div></>}</Wrap>;

const PollingSlide = ({ slide: s }) => { const [msgs, setMsgs] = useState([]); const [tick, setTick] = useState(0); const fm = [{ user: "Alice", text: "Hey everyone!", server: "Pi-Alice" }, { user: "Bob", text: "Whoa this works!", server: "Pi-Bob" }, { user: "Charlie", text: "Hello from my Pi 🎉", server: "Pi-Charlie" }, { user: "Alice", text: "Can you see this?", server: "Pi-Alice" }, { user: "Dana", text: "This is so cool", server: "Pi-Dana" }]; useEffect(() => { setMsgs([]); setTick(0); const id = setInterval(() => setTick(t => t + 1), 2000); return () => clearInterval(id); }, []); useEffect(() => { if (tick > 0 && tick <= fm.length) setMsgs(p => [...p, fm[tick - 1]]); if (tick > fm.length + 2) { setTick(0); setMsgs([]); } }, [tick]); return <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.description} /><div style={{ display: "flex", gap: 12, marginBottom: 16 }}><div style={{ flex: 1, background: "rgba(34,211,238,0.05)", border: "1px solid rgba(34,211,238,0.15)", borderRadius: 12, padding: 14 }}><div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "#22d3ee", marginBottom: 10, fontWeight: 700 }}>📱 Phone</div><div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "rgba(255,255,255,0.5)" }}>GET /api/messages?after={msgs.length}<br /><span style={{ color: tick % 2 === 0 ? "#4ade80" : "rgba(255,255,255,0.3)" }}>● polling...</span></div></div><div style={{ flex: 1, background: "rgba(167,139,250,0.05)", border: "1px solid rgba(167,139,250,0.15)", borderRadius: 12, padding: 14 }}><div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "#a78bfa", marginBottom: 10, fontWeight: 700 }}>🍳 Pi</div><div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "rgba(255,255,255,0.5)" }}>200 OK<br />{`[${msgs.length} msgs]`}</div></div></div><div style={{ background: "rgba(0,0,0,0.4)", borderRadius: 12, border: "1px solid rgba(255,255,255,0.06)", padding: 14, height: 200, overflowY: "auto" }}>{msgs.map((m, i) => <div key={i} style={{ background: "rgba(255,255,255,0.04)", borderRadius: 8, padding: "8px 12px", marginBottom: 6, animation: "fadeIn 0.3s ease" }}><span style={{ fontWeight: 700, color: "#22d3ee", fontSize: 13 }}>{m.user}</span><span style={{ color: "rgba(255,255,255,0.3)", fontSize: 10, marginLeft: 6 }}>@{m.server}</span><div style={{ color: "rgba(255,255,255,0.7)", fontSize: 13, marginTop: 2 }}>{m.text}</div></div>)}{msgs.length === 0 && <div style={{ color: "rgba(255,255,255,0.2)", fontSize: 13, textAlign: "center", marginTop: 60 }}>Waiting for messages...</div>}</div><style>{`@keyframes fadeIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}`}</style></Wrap>; };

const HubExplainerSlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.subtitle} /><div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 20 }}>{s.steps.map((st, i) => <div key={i} style={{ display: "flex", gap: 14, alignItems: "center", background: "rgba(255,255,255,0.03)", borderRadius: 10, padding: "12px 16px" }}><div style={{ width: 32, height: 32, borderRadius: "50%", background: "rgba(167,139,250,0.12)", border: "1px solid rgba(167,139,250,0.3)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--mono)", fontSize: 14, fontWeight: 800, color: "#a78bfa", flexShrink: 0 }}>{st.num}</div><span style={{ fontSize: 22, flexShrink: 0 }}>{st.icon}</span><span style={{ color: "rgba(255,255,255,0.7)", fontSize: 14, lineHeight: 1.4 }}>{st.text}</span></div>)}</div><InsightBox text={s.key_insight} /></Wrap>;

const FileMapSlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.subtitle} /><div style={{ display: "flex", flexDirection: "column", gap: 14 }}>{s.files.map((f, i) => <div key={i} style={{ background: `${f.color}06`, border: `1px solid ${f.color}20`, borderRadius: 14, padding: "18px 20px" }}><div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}><span style={{ fontSize: 22 }}>{f.icon}</span><code style={{ fontFamily: "var(--mono)", fontSize: 16, fontWeight: 700, color: f.color }}>{f.name}</code><span style={{ fontFamily: "var(--mono)", fontSize: 10, color: "rgba(255,255,255,0.4)", background: "rgba(255,255,255,0.06)", padding: "2px 8px", borderRadius: 4, marginLeft: "auto" }}>{f.role}</span></div><p style={{ color: "rgba(255,255,255,0.5)", fontSize: 13, lineHeight: 1.5, marginLeft: 32 }}>{f.desc}</p></div>)}</div></Wrap>;

const ChallengeSlide = ({ slide: s }) => <Wrap><PhaseBadge phase={s.phase} /><Heading emoji={s.emoji} title={s.title} />{s.tasks.map((t, i) => <div key={i} style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 12, padding: "16px 18px", marginBottom: 12 }}><div style={{ color: "#fff", fontSize: 15, fontWeight: 700, marginBottom: 10 }}>{t.label}</div><div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "rgba(255,255,255,0.4)", marginBottom: 6 }}>File: {t.file}</div><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><div style={{ flex: 1, minWidth: 160, background: "rgba(248,113,113,0.08)", border: "1px solid rgba(248,113,113,0.2)", borderRadius: 8, padding: "8px 12px" }}><div style={{ fontSize: 10, color: "#f87171", fontFamily: "var(--mono)", marginBottom: 4 }}>FIND</div><code style={{ color: "#fca5a5", fontSize: 12, fontFamily: "var(--mono)", wordBreak: "break-all" }}>{t.find}</code></div><div style={{ flex: 1, minWidth: 160, background: "rgba(74,222,128,0.08)", border: "1px solid rgba(74,222,128,0.2)", borderRadius: 8, padding: "8px 12px" }}><div style={{ fontSize: 10, color: "#4ade80", fontFamily: "var(--mono)", marginBottom: 4 }}>REPLACE</div><code style={{ color: "#86efac", fontSize: 12, fontFamily: "var(--mono)", whiteSpace: "pre-wrap", wordBreak: "break-all" }}>{t.replace}</code></div></div></div>)}{s.colors && s.colors.length > 0 && <div style={{ marginTop: 16, display: "flex", gap: 8, flexWrap: "wrap" }}>{s.colors.map((c, i) => <div key={i} style={{ display: "flex", alignItems: "center", gap: 8, background: "rgba(0,0,0,0.3)", borderRadius: 8, padding: "6px 12px" }}><div style={{ width: 16, height: 16, borderRadius: 4, background: c.hex }} /><span style={{ fontFamily: "var(--mono)", fontSize: 12, color: "rgba(255,255,255,0.5)" }}>{c.hex}</span><span style={{ fontSize: 11, color: "rgba(255,255,255,0.3)" }}>{c.name}</span></div>)}</div>}{s.editorSteps && s.editorSteps.length > 0 && <div style={{ marginTop: 16, background: "rgba(0,0,0,0.3)", borderRadius: 10, padding: "14px 16px" }}><div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "rgba(255,255,255,0.3)", marginBottom: 8 }}>STEPS</div>{s.editorSteps.map((st, i) => <div key={i} style={{ color: "rgba(255,255,255,0.6)", fontSize: 13, fontFamily: "var(--mono)", padding: "3px 0" }}><span style={{ color: "#22d3ee", marginRight: 8 }}>{i + 1}.</span>{st}</div>)}</div>}{s.followUp && <InsightBox text={s.followUp} />}</Wrap>;

const JourneySlide = ({ slide: s }) => { const steps = [{ n: 1, i: "📱", t: "You type \"hello\" and tap Send", v: "POST", c: "#22d3ee" }, { n: 2, i: "📡", t: "Phone sends POST to your Pi's /api/send", v: "POST", c: "#22d3ee" }, { n: 3, i: "🍳", t: "Pi saves message and forwards to Hub", v: "POST", c: "#a78bfa" }, { n: 4, i: "🌐", t: "Hub sends POST to every other Pi", v: "POST", c: "#a78bfa" }, { n: 5, i: "🍳", t: "Each Pi saves the incoming message", v: "—", c: "#fb923c" }, { n: 6, i: "📱", t: "Every 2s, phones GET /api/messages", v: "GET", c: "#4ade80" }, { n: 7, i: "🍳", t: "Pi responds with new messages as JSON", v: "200", c: "#4ade80" }, { n: 8, i: "📱", t: "JavaScript renders them on screen", v: "—", c: "#fbbf24" }]; return <Wrap><Heading emoji={s.emoji} title={s.title} subtitle={s.description} />{steps.map((st, idx) => <div key={idx} style={{ display: "flex", gap: 14, marginBottom: 2 }}><div style={{ display: "flex", flexDirection: "column", alignItems: "center", width: 36 }}><div style={{ width: 30, height: 30, borderRadius: "50%", background: `${st.c}18`, border: `1.5px solid ${st.c}50`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontFamily: "var(--mono)", fontWeight: 800, color: st.c, flexShrink: 0 }}>{st.n}</div>{idx < steps.length - 1 && <div style={{ width: 1.5, flex: 1, minHeight: 10, background: `${st.c}25` }} />}</div><div style={{ paddingBottom: 14, flex: 1, display: "flex", alignItems: "center", gap: 10 }}><span style={{ fontSize: 18 }}>{st.i}</span><span style={{ color: "rgba(255,255,255,0.75)", fontSize: 13, flex: 1 }}>{st.t}</span>{st.v !== "—" && <span style={{ fontFamily: "var(--mono)", fontSize: 10, background: `${st.c}15`, color: st.c, padding: "2px 8px", borderRadius: 5, fontWeight: 700 }}>{st.v}</span>}</div></div>)}</Wrap>; };

const RealWorldSlide = ({ slide: s }) => <Wrap><Heading emoji={s.emoji} title={s.title} /><div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{s.comparisons.map((c, i) => <div key={i} style={{ display: "flex", alignItems: "center", gap: 10, background: "rgba(255,255,255,0.03)", borderRadius: 10, padding: "12px 16px" }}><div style={{ flex: 1, textAlign: "right" }}><div style={{ color: "#22d3ee", fontSize: 13, fontFamily: "var(--mono)", fontWeight: 600 }}>{c.you}</div></div><div style={{ background: "rgba(255,255,255,0.08)", borderRadius: 6, padding: "3px 10px", fontFamily: "var(--mono)", fontSize: 9, color: "rgba(255,255,255,0.4)", fontWeight: 700, textTransform: "uppercase", letterSpacing: 1 }}>{c.label}</div><div style={{ flex: 1 }}><div style={{ color: "#a78bfa", fontSize: 13, fontFamily: "var(--mono)", fontWeight: 600 }}>{c.real}</div></div></div>)}</div><div style={{ marginTop: 28, textAlign: "center", background: "linear-gradient(135deg, rgba(34,211,238,0.08), rgba(167,139,250,0.08))", border: "1px solid rgba(167,139,250,0.2)", borderRadius: 14, padding: "20px 24px" }}><p style={{ color: "#fff", fontSize: 18, fontWeight: 700, lineHeight: 1.4, fontFamily: "var(--mono)" }}>{s.punchline}</p></div></Wrap>;

const WrapupSlide = ({ slide: s }) => <div style={{ padding: "60px 24px", maxWidth: 600, margin: "0 auto", textAlign: "center" }}><div style={{ fontSize: 56, marginBottom: 16 }}>{s.emoji}</div><h2 style={{ fontSize: 30, fontWeight: 800, color: "#fff", marginBottom: 28, fontFamily: "var(--mono)" }}>{s.title}</h2><div style={{ display: "flex", flexDirection: "column", gap: 10, textAlign: "left" }}>{s.achievements.map((a, i) => <div key={i} style={{ display: "flex", gap: 14, alignItems: "center", background: "rgba(255,255,255,0.03)", borderRadius: 10, padding: "14px 16px" }}><span style={{ fontSize: 24 }}>{a.icon}</span><span style={{ color: "#fff", fontSize: 15, fontWeight: 500 }}>{a.text}</span></div>)}</div><div style={{ marginTop: 32, background: "linear-gradient(135deg, rgba(34,211,238,0.08), rgba(251,146,60,0.08))", border: "1px solid rgba(34,211,238,0.2)", borderRadius: 14, padding: "20px 24px" }}><p style={{ color: "rgba(255,255,255,0.7)", fontSize: 16, lineHeight: 1.6 }}>{s.closing}</p></div></div>;

const PiTableSlide = ({ slide: s }) => <Wrap><PhaseBadge phase={s.phase} /><Heading emoji={s.emoji} title={s.title} subtitle={s.subtitle} /><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: 8, marginBottom: 16 }}>{s.pis.map((p, i) => <div key={i} style={{ background: "rgba(34,211,238,0.06)", border: "1px solid rgba(34,211,238,0.15)", borderRadius: 10, padding: "10px 14px" }}><div style={{ fontFamily: "var(--mono)", fontSize: 12, fontWeight: 700, color: "#a78bfa", marginBottom: 4 }}>{p.name}</div><code style={{ fontFamily: "var(--mono)", fontSize: 13, color: "#22d3ee", wordBreak: "break-all" }}>{p.cmd}</code></div>)}</div><div style={{ background: "rgba(251,191,36,0.08)", border: "1px solid rgba(251,191,36,0.25)", borderRadius: 10, padding: "14px 18px", marginBottom: 16, display: "flex", gap: 12, alignItems: "center" }}><span style={{ fontSize: 20 }}>🔑</span><span style={{ color: "#fde68a", fontSize: 15, fontFamily: "var(--mono)", fontWeight: 600 }}>Password: {s.password}</span></div>{s.breakdown && s.breakdown.length > 0 && <div style={{ marginBottom: 16, display: "flex", flexDirection: "column", gap: 6 }}>{s.breakdown.map((b, i) => <div key={i} style={{ display: "flex", gap: 12, alignItems: "baseline" }}><code style={{ fontFamily: "var(--mono)", fontSize: 13, color: "#22d3ee", flexShrink: 0, background: "rgba(0,0,0,0.3)", padding: "2px 8px", borderRadius: 4 }}>{b.piece}</code><span style={{ color: "rgba(255,255,255,0.5)", fontSize: 13 }}>{b.desc}</span></div>)}</div>}{s.warnings.map((w, i) => <div key={i} style={{ background: "rgba(251,191,36,0.06)", border: "1px solid rgba(251,191,36,0.2)", borderRadius: 10, padding: "14px 16px", marginBottom: 8, display: "flex", gap: 12 }}><span style={{ fontSize: 18 }}>{w.icon}</span><div><div style={{ color: "#fbbf24", fontSize: 14, fontWeight: 700 }}>{w.title}</div><div style={{ color: "rgba(255,255,255,0.55)", fontSize: 13, marginTop: 3, lineHeight: 1.4 }}>{w.fix}</div></div></div>)}<CheckpointBox text={s.checkpoint} /></Wrap>;

const SLIDE_MAP = { title: TitleSlide, overview: OverviewSlide, analogy: AnalogySlide, "analogy-flow": AnalogyFlowSlide, explainer: ExplainerSlide, codes: CodesSlide, versus: VersusSlide, "json-explainer": JsonExplainerSlide, architecture: ArchitectureSlide, step: StepSlide, "code-step": CodeStepSlide, magic: MagicSlide, "request-trace": RequestTraceSlide, "code-anatomy": CodeAnatomySlide, "polling-demo": PollingSlide, "hub-explainer": HubExplainerSlide, "file-map": FileMapSlide, challenge: ChallengeSlide, journey: JourneySlide, realworld: RealWorldSlide, wrapup: WrapupSlide, "pi-table": PiTableSlide };

export default function App() {
  const [current, setCurrent] = useState(0);
  const [fade, setFade] = useState(true);
  const touchRef = useRef(null);
  const go = useCallback((d) => { const n = current + d; if (n < 0 || n >= SLIDES.length) return; setFade(false); setTimeout(() => { setCurrent(n); setFade(true); }, 180); }, [current]);
  useEffect(() => { const h = (e) => { if (e.key === "ArrowRight" || e.key === " ") { e.preventDefault(); go(1); } if (e.key === "ArrowLeft") { e.preventDefault(); go(-1); } }; window.addEventListener("keydown", h); return () => window.removeEventListener("keydown", h); }, [go]);
  const Comp = SLIDE_MAP[SLIDES[current].type];
  return <div onTouchStart={e => { touchRef.current = e.touches[0].clientX; }} onTouchEnd={e => { if (touchRef.current === null) return; const d = touchRef.current - e.changedTouches[0].clientX; if (Math.abs(d) > 50) go(d > 0 ? 1 : -1); touchRef.current = null; }} style={{ "--mono": "'JetBrains Mono', monospace", minHeight: "100vh", background: "linear-gradient(170deg, #0c0c1d 0%, #111127 40%, #0e1a2b 100%)", color: "#fff", fontFamily: "'DM Sans', -apple-system, sans-serif", overflowX: "hidden", paddingBottom: 60 }}>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=JetBrains+Mono:wght@400;600;700;800&display=swap" rel="stylesheet" />
    <ProgressBar current={current} total={SLIDES.length} />
    <div style={{ opacity: fade ? 1 : 0, transform: fade ? "translateY(0)" : "translateY(8px)", transition: "opacity 0.2s ease, transform 0.2s ease" }}>{Comp && <Comp slide={SLIDES[current]} />}</div>
    <SlideNav current={current} total={SLIDES.length} onPrev={() => go(-1)} onNext={() => go(1)} />
  </div>;
}
